"""empty message

Revision ID: 4acf9823467e
Revises: 
Create Date: 2024-05-27 16:17:10.069292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acf9823467e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_name'), ['name'], unique=False)

    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)

    op.create_table('user_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('cabinet_number', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=60), nullable=False, comment='Канал откуда пришло обращение'),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_request_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_request_closed_at'), ['closed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_request_executor_id'), ['executor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_request_status_id'), ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_request_user_id'), ['user_id'], unique=False)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('user_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_request_id'], ['user_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_executor_id'), ['executor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_user_request_id'), ['user_request_id'], unique=False)

    op.create_table('user_request_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('user_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['user_request_id'], ['user_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_request_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_request_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_request_history_executor_id'), ['executor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_request_history_status_id'), ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_request_history_user_request_id'), ['user_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_request_history_user_request_id'))
        batch_op.drop_index(batch_op.f('ix_user_request_history_status_id'))
        batch_op.drop_index(batch_op.f('ix_user_request_history_executor_id'))
        batch_op.drop_index(batch_op.f('ix_user_request_history_created_at'))

    op.drop_table('user_request_history')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_user_request_id'))
        batch_op.drop_index(batch_op.f('ix_comment_executor_id'))
        batch_op.drop_index(batch_op.f('ix_comment_created_at'))

    op.drop_table('comment')
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_request_status_id'))
        batch_op.drop_index(batch_op.f('ix_user_request_executor_id'))
        batch_op.drop_index(batch_op.f('ix_user_request_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_request_closed_at'))
        batch_op.drop_index(batch_op.f('ix_user_request_branch_id'))

    op.drop_table('user_request')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_name'))
        batch_op.drop_index(batch_op.f('ix_status_created_at'))

    op.drop_table('status')
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_name'))
        batch_op.drop_index(batch_op.f('ix_branch_created_at'))

    op.drop_table('branch')
    # ### end Alembic commands ###
