"""empty message

Revision ID: cf330b10b101
Revises: 4acf9823467e
Create Date: 2024-06-16 21:02:16.280356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf330b10b101'
down_revision = '4acf9823467e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theme_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_theme_name'), ['name'], unique=False)

    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_request_theme_id'), ['theme_id'], unique=False)
        batch_op.create_foreign_key(None, 'theme', ['theme_id'], ['id'])
        batch_op.drop_column('theme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_request_theme_id'))
        batch_op.drop_column('theme_id')

    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theme_name'))
        batch_op.drop_index(batch_op.f('ix_theme_created_at'))

    op.drop_table('theme')
    # ### end Alembic commands ###
